/**
 * seed.ts — GradPlanner database seeder
 *
 * Seeds UniversityRanking from the preprocessed merged CSV
 * (notebook/universities.csv — generated by notebook/preprocess.py).
 *
 * Run with:  pnpm exec prisma db seed
 */

import { createReadStream } from "fs";
import { parse } from "csv-parse";
import path from "path";
import { prisma } from "../src/lib/prisma.js";
import { seedCountryIntelligence } from "./seed_country_intelligence.js";

const CSV_PATH = path.resolve(
  path.dirname(new URL(import.meta.url).pathname.replace(/^\/([a-zA-Z]:\/)/, "$1")),
  "../../notebook/universities.csv"
);

type RawRow = {
  institution_name: string;
  country: string;
  region: string;
  in_qs: string;
  in_the: string;
  in_arwu: string;
  qs_2026_rank: string;
  qs_2026_rank_display: string;
  qs_2026_score: string;
  qs_ar_score: string;
  qs_er_score: string;
  qs_fsr_score: string;
  qs_cpf_score: string;
  qs_ifr_score: string;
  qs_isr_score: string;
  qs_eo_score: string;
  qs_sus_score: string;
  the_2026_rank: string;
  the_2026_rank_display: string;
  the_2026_score: string;
  the_teaching: string;
  the_research_env: string;
  the_research_quality: string;
  the_industry: string;
  the_international: string;
  arwu_2025_rank: string;
  arwu_2025_score: string;
  arwu_alumni: string;
  arwu_award: string;
  arwu_hici: string;
  arwu_ns: string;
  arwu_pub: string;
  arwu_pcp: string;
};

function toInt(v: string): number | null {
  const n = parseInt(v, 10);
  return isNaN(n) ? null : n;
}

function toFloat(v: string): number | null {
  if (!v || v === "None" || v === "") return null;
  const n = parseFloat(v);
  return isNaN(n) ? null : n;
}

function toBool(v: string): boolean {
  return v === "True" || v === "true" || v === "1";
}

async function readCsv(filePath: string): Promise<RawRow[]> {
  return new Promise((resolve, reject) => {
    const rows: RawRow[] = [];
    createReadStream(filePath)
      .pipe(parse({ columns: true, skip_empty_lines: true, bom: true }))
      .on("data", (row: RawRow) => rows.push(row))
      .on("end", () => resolve(rows))
      .on("error", reject);
  });
}

async function main() {
  console.log("🌱 Starting seed...");
  console.log(`   Reading: ${CSV_PATH}`);

  const rows = await readCsv(CSV_PATH);
  console.log(`   Loaded ${rows.length} universities from merged CSV`);

  // ── Clear existing ranking data ──────────────────────────────────────────
  const deleted = await prisma.universityRanking.deleteMany();
  console.log(`   Cleared ${deleted.count} existing rows`);

  // ── Bulk insert in batches of 500 ────────────────────────────────────────
  const BATCH = 500;
  let inserted = 0;

  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);

    await prisma.universityRanking.createMany({
      data: batch.map((r) => ({
        institutionName:    r.institution_name,
        country:            r.country,
        region:             r.region || null,
        inQs:               toBool(r.in_qs),
        inThe:              toBool(r.in_the),
        inArwu:             toBool(r.in_arwu),

        // QS 2026
        qs2026Rank:         toInt(r.qs_2026_rank),
        qs2026RankDisplay:  r.qs_2026_rank_display || null,
        qs2026Score:        toFloat(r.qs_2026_score),
        qsArScore:          toFloat(r.qs_ar_score),
        qsErScore:          toFloat(r.qs_er_score),
        qsFsrScore:         toFloat(r.qs_fsr_score),
        qsCpfScore:         toFloat(r.qs_cpf_score),
        qsIfrScore:         toFloat(r.qs_ifr_score),
        qsIsrScore:         toFloat(r.qs_isr_score),
        qsEoScore:          toFloat(r.qs_eo_score),
        qsSusScore:         toFloat(r.qs_sus_score),

        // THE 2026
        the2026Rank:        toInt(r.the_2026_rank),
        the2026RankDisplay: r.the_2026_rank_display || null,
        the2026Score:       toFloat(r.the_2026_score),
        theTeaching:        toFloat(r.the_teaching),
        theResearchEnv:     toFloat(r.the_research_env),
        theResearchQuality: toFloat(r.the_research_quality),
        theIndustry:        toFloat(r.the_industry),
        theInternational:   toFloat(r.the_international),

        // ARWU 2025
        arwu2025Rank:  toInt(r.arwu_2025_rank),
        arwu2025Score: toFloat(r.arwu_2025_score),
        arwuAlumni:    toFloat(r.arwu_alumni),
        arwuAward:     toFloat(r.arwu_award),
        arwuHici:      toFloat(r.arwu_hici),
        arwuNs:        toFloat(r.arwu_ns),
        arwuPub:       toFloat(r.arwu_pub),
        arwuPcp:       toFloat(r.arwu_pcp),
      })),
      skipDuplicates: true,
    });

    inserted += batch.length;
    process.stdout.write(`   Inserted ${inserted}/${rows.length}...\r`);
  }

  console.log(`\n   Done! Inserted ${inserted} university ranking rows.`);

  // ── Summary stats ────────────────────────────────────────────────────────
  const total  = await prisma.universityRanking.count();
  const inAll3 = await prisma.universityRanking.count({ where: { inQs: true, inThe: true, inArwu: true } });
  const inQs   = await prisma.universityRanking.count({ where: { inQs: true } });
  const inThe  = await prisma.universityRanking.count({ where: { inThe: true } });
  const inArwu = await prisma.universityRanking.count({ where: { inArwu: true } });

  console.log("\n📊 Seeding summary:");
  console.log(`   Total rows in DB          : ${total}`);
  console.log(`   Ranked in QS 2026         : ${inQs}`);
  console.log(`   Ranked in THE 2026        : ${inThe}`);
  console.log(`   Ranked in ARWU 2025       : ${inArwu}`);
  console.log(`   Ranked in ALL 3 systems   : ${inAll3}`);

  // Seed Country Intelligence reference data
  await seedCountryIntelligence();

  console.log("\n✅ Seed complete!");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
