"use client";

import React, { useState } from "react";
import Link from "next/link";
import {
  CheckCircle2,
  AlertCircle,
  Calendar,
  ChevronDown,
  ChevronUp,
  GraduationCap,
  Clock,
  ArrowRight,
  Sparkles,
  Check,
  AlertTriangle,
  Info,
  ExternalLink,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

interface Task {
  id: string;
  title: string;
  description: string;
  type: "PROFESSOR_FOLLOWUP" | "DOCUMENT_DELAY" | "SCHOLARSHIP_DEADLINE" | "PROFILE_GAP";
  urgency: "HIGH" | "MEDIUM" | "LOW";
  link: string;
  meta?: any;
}

interface CriteriaDetail {
  met: boolean;
  required: number | null;
  actual: number | null;
}

interface UniversityReadiness {
  universityId: string;
  universityName: string;
  country: string;
  program: string;
  tier: "DREAM" | "MATCH" | "SAFETY";
  readinessScore: number;
  status: "APPLY_NOW" | "PREPARE_MORE" | "TOO_EARLY" | "IN_PROGRESS";
  deadline: string | null;
  daysRemaining: number | null;
  criteria: {
    cgpa: CriteriaDetail;
    ielts: CriteriaDetail;
    documents: {
      met: boolean;
      missing: string[];
      totalCount: number;
      obtainedCount: number;
    };
  };
}

interface DecisionEngineData {
  tasks: Task[];
  readiness: UniversityReadiness[];
  summary: {
    totalApplicationsTracked: number;
    averageReadiness: number;
    highUrgencyTasksCount: number;
  };
}

interface WhatNextTodayProps {
  data: DecisionEngineData | null;
  loading: boolean;
}

const URGENCY_STYLES = {
  HIGH: {
    border: "border-destructive/30 bg-destructive/5 hover:border-destructive/60",
    badge: "bg-destructive/15 text-destructive border-destructive/20",
    text: "text-destructive",
  },
  MEDIUM: {
    border: "border-amber-500/30 bg-amber-500/5 hover:border-amber-500/60",
    badge: "bg-amber-500/15 text-amber-400 border-amber-500/20",
    text: "text-amber-500",
  },
  LOW: {
    border: "border-border/60 bg-muted/20 hover:border-border",
    badge: "bg-muted text-muted-foreground border-border/40",
    text: "text-muted-foreground",
  },
};

const STATUS_BADGES = {
  APPLY_NOW: {
    label: "✅ Apply Now",
    style: "bg-emerald-500/10 border-emerald-500/30 text-emerald-400 font-bold",
  },
  PREPARE_MORE: {
    label: "🟡 Prepare Profile/Docs",
    style: "bg-amber-500/10 border-amber-500/30 text-amber-400 font-semibold",
  },
  TOO_EARLY: {
    label: "💤 Too Early",
    style: "bg-slate-500/10 border-slate-500/30 text-slate-400 font-medium",
  },
  IN_PROGRESS: {
    label: "⏳ In Progress",
    style: "bg-blue-500/10 border-blue-500/30 text-blue-400 font-semibold",
  },
};

export function WhatNextToday({ data, loading }: WhatNextTodayProps) {
  const [expandedUniId, setExpandedUniId] = useState<string | null>(null);

  if (loading) {
    return (
      <div className="flex h-40 items-center justify-center border border-border/60 bg-card/10 rounded-2xl">
        <Clock className="h-6 w-6 animate-spin text-primary mr-2" />
        <span className="text-sm text-muted-foreground font-medium">Computing your next actions...</span>
      </div>
    );
  }

  if (!data) return null;

  const { tasks, readiness, summary } = data;

  const toggleUniExpand = (id: string) => {
    setExpandedUniId((prev) => (prev === id ? null : id));
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-5 gap-8 animate-in fade-in duration-500">
      
      {/* Column A: Smart Daily Tasks Checklist (3/5 wide) */}
      <Card className="border-border/60 bg-card/30 backdrop-blur-md lg:col-span-3 flex flex-col h-full shadow-lg">
        <CardHeader className="pb-4">
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-lg font-bold text-foreground flex items-center gap-2">
                <Sparkles className="h-5 w-5 text-primary" />
                What Next Today
              </CardTitle>
              <CardDescription className="text-xs text-muted-foreground">
                Your personalized action checklist generated by the admissions advisor.
              </CardDescription>
            </div>
            {summary.highUrgencyTasksCount > 0 && (
              <span className="text-[10px] font-black px-2.5 py-0.5 rounded-full bg-destructive/15 text-destructive border border-destructive/30 animate-pulse">
                {summary.highUrgencyTasksCount} Action{summary.highUrgencyTasksCount > 1 ? "s" : ""} Required
              </span>
            )}
          </div>
        </CardHeader>
        <CardContent className="space-y-4 flex-1">
          {tasks.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-center space-y-3">
              <div className="p-3 bg-emerald-500/10 rounded-full text-emerald-400 border border-emerald-500/20">
                <Check className="h-6 w-6" />
              </div>
              <div>
                <p className="font-bold text-sm text-foreground">You are fully caught up!</p>
                <p className="text-xs text-muted-foreground max-w-sm mt-1">
                  All profile details are filled, documents are in order, and professor outreach cadences are satisfied.
                </p>
              </div>
            </div>
          ) : (
            <div className="space-y-3">
              {tasks.map((task) => {
                const styles = URGENCY_STYLES[task.urgency];
                return (
                  <div
                    key={task.id}
                    className={`flex flex-col sm:flex-row sm:items-start justify-between p-4 border rounded-xl gap-4 transition-all duration-300 ${styles.border}`}
                  >
                    <div className="space-y-1.5 min-w-0">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className={`text-[9px] font-extrabold tracking-wider px-2 py-0.5 rounded-full border ${styles.badge}`}>
                          {task.urgency}
                        </span>
                        <span className="text-[10px] text-muted-foreground font-semibold uppercase tracking-wider">
                          {task.type.replace("_", " ")}
                        </span>
                      </div>
                      <h4 className="text-sm font-bold text-foreground leading-snug">
                        {task.title}
                      </h4>
                      <p className="text-xs text-muted-foreground leading-relaxed">
                        {task.description}
                      </p>
                    </div>

                    <Link href={task.link} className="shrink-0 self-end sm:self-center">
                      <Button
                        variant="outline"
                        size="sm"
                        className="h-8 border-border text-foreground hover:bg-primary hover:text-primary-foreground font-bold text-[11px] px-3.5 transition-all cursor-pointer flex items-center gap-1"
                      >
                        Resolve
                        <ArrowRight className="h-3 w-3" />
                      </Button>
                    </Link>
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Column B: University Readiness & Badges (2/5 wide) */}
      <Card className="border-border/60 bg-card/30 backdrop-blur-md lg:col-span-2 flex flex-col h-full shadow-lg">
        <CardHeader className="pb-4">
          <div>
            <CardTitle className="text-lg font-bold text-foreground flex items-center gap-2">
              <GraduationCap className="h-5 w-5 text-primary" />
              University Readiness
            </CardTitle>
            <CardDescription className="text-xs text-muted-foreground">
              Score matching your CGPA, IELTS, and checklist against tracked universities.
            </CardDescription>
          </div>
        </CardHeader>
        <CardContent className="space-y-4 flex-1">
          {readiness.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-center space-y-3">
              <div className="p-3 bg-primary/10 rounded-full text-primary border border-primary/20">
                <GraduationCap className="h-6 w-6" />
              </div>
              <div>
                <p className="font-bold text-sm text-foreground">No Tracked Universities</p>
                <p className="text-xs text-muted-foreground max-w-sm mt-1">
                  Add target universities in your universities list to compute profile compatibility and check document checklists.
                </p>
              </div>
              <Link href="/dashboard/universities">
                <Button size="sm" className="h-8 text-xs bg-primary text-primary-foreground">
                  Track Universities
                </Button>
              </Link>
            </div>
          ) : (
            <div className="space-y-3 overflow-y-auto max-h-[480px] pr-1">
              {readiness.map((item) => {
                const badge = STATUS_BADGES[item.status];
                const isExpanded = expandedUniId === item.universityId;

                // Determine bar color
                let progressColor = "bg-rose-500";
                if (item.readinessScore >= 75) {
                  progressColor = "bg-emerald-400";
                } else if (item.readinessScore >= 40) {
                  progressColor = "bg-amber-400";
                }

                return (
                  <div
                    key={item.universityId}
                    className="p-3.5 border border-border/60 bg-muted/10 rounded-xl space-y-3 hover:border-border transition-all duration-300"
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div className="min-w-0">
                        <h4 className="text-xs font-bold text-foreground truncate">{item.universityName}</h4>
                        <span className="text-[10px] text-muted-foreground">
                          {item.country} · {item.program}
                        </span>
                      </div>
                      <span className={`text-[9px] px-2 py-0.5 rounded-full border shrink-0 ${badge.style}`}>
                        {badge.label}
                      </span>
                    </div>

                    {/* Progress Bar */}
                    <div className="space-y-1">
                      <div className="flex justify-between text-[10px] font-bold text-muted-foreground">
                        <span>Readiness Fit</span>
                        <span className={item.readinessScore >= 75 ? "text-emerald-400" : item.readinessScore >= 40 ? "text-amber-400" : "text-rose-500"}>
                          {item.readinessScore}%
                        </span>
                      </div>
                      <div className="w-full bg-accent rounded-full h-1.5">
                        <div
                          className={`h-1.5 rounded-full transition-all duration-500 ${progressColor}`}
                          style={{ width: `${item.readinessScore}%` }}
                        />
                      </div>
                    </div>

                    {/* Deadline details and toggle */}
                    <div className="flex items-center justify-between text-[10px] text-muted-foreground pt-1 border-t border-border/20">
                      <div>
                        {item.daysRemaining !== null ? (
                          <span className={item.daysRemaining <= 30 ? "text-destructive font-semibold" : ""}>
                            {item.daysRemaining <= 0 ? "Deadline passed" : `Deadline: ${item.daysRemaining} days remaining`}
                          </span>
                        ) : (
                          <span>No deadline set</span>
                        )}
                      </div>

                      <button
                        onClick={() => toggleUniExpand(item.universityId)}
                        className="text-primary hover:underline flex items-center gap-0.5"
                      >
                        {isExpanded ? (
                          <>Hide criteria <ChevronUp className="h-3 w-3" /></>
                        ) : (
                          <>Check criteria <ChevronDown className="h-3 w-3" /></>
                        )}
                      </button>
                    </div>

                    {/* Detailed criteria checklist when expanded */}
                    {isExpanded && (
                      <div className="p-3 bg-background border border-border/40 rounded-lg space-y-2 text-xs text-muted-foreground animate-in slide-in-from-top-2 duration-200">
                        <div className="font-semibold text-[10px] text-foreground uppercase tracking-wider mb-1">
                          Admissions Requirements Match
                        </div>
                        
                        {/* CGPA Match */}
                        <div className="flex items-center justify-between">
                          <span>CGPA Check:</span>
                          <span className="font-bold flex items-center gap-1">
                            {item.criteria.cgpa.required ? (
                              <>
                                {item.criteria.cgpa.met ? (
                                  <span className="text-emerald-400">✓ Met ({item.criteria.cgpa.actual} &gt;= {item.criteria.cgpa.required})</span>
                                ) : (
                                  <span className="text-destructive flex items-center gap-0.5">
                                    <AlertTriangle className="h-3 w-3 inline" />
                                    Gap ({item.criteria.cgpa.actual || "N/A"} &lt; {item.criteria.cgpa.required})
                                  </span>
                                )}
                              </>
                            ) : (
                              <span className="text-muted-foreground font-normal">✓ No cutoff requirement</span>
                            )}
                          </span>
                        </div>

                        {/* IELTS Match */}
                        <div className="flex items-center justify-between">
                          <span>IELTS Check:</span>
                          <span className="font-bold flex items-center gap-1">
                            {item.criteria.ielts.required ? (
                              <>
                                {item.criteria.ielts.met ? (
                                  <span className="text-emerald-400">✓ Met ({item.criteria.ielts.actual} &gt;= {item.criteria.ielts.required})</span>
                                ) : (
                                  <span className="text-destructive flex items-center gap-0.5">
                                    <AlertTriangle className="h-3 w-3 inline" />
                                    Gap ({item.criteria.ielts.actual || "N/A"} &lt; {item.criteria.ielts.required})
                                  </span>
                                )}
                              </>
                            ) : (
                              <span className="text-muted-foreground font-normal">✓ No cutoff requirement</span>
                            )}
                          </span>
                        </div>

                        {/* Documents Checklist */}
                        <div className="pt-1.5 border-t border-border/20">
                          <div className="flex justify-between font-semibold mb-1">
                            <span>Document Vault Checklist:</span>
                            <span className={item.criteria.documents.met ? "text-emerald-400" : "text-amber-400"}>
                              {item.criteria.documents.obtainedCount} / {item.criteria.documents.totalCount} obtained
                            </span>
                          </div>
                          {item.criteria.documents.missing.length > 0 ? (
                            <div className="space-y-1 mt-1 text-[11px] bg-amber-500/5 border border-amber-500/10 p-2 rounded-md">
                              <p className="text-amber-500 font-medium">Missing/Pending documents:</p>
                              <ul className="list-disc list-inside space-y-0.5 pl-1">
                                {item.criteria.documents.missing.map((doc, idx) => (
                                  <li key={idx}>{doc}</li>
                                ))}
                              </ul>
                            </div>
                          ) : (
                            <p className="text-emerald-400 text-[11px] font-semibold mt-1">✓ All required documents uploaded</p>
                          )}
                        </div>

                        {/* Germany APS Alert */}
                        {item.country.toLowerCase().includes("germany") && item.criteria.documents.missing.includes("APS Certificate") && (
                          <div className="p-2 bg-destructive/10 border border-destructive/20 text-[10px] text-destructive rounded-md flex items-start gap-1">
                            <Info className="h-3.5 w-3.5 mt-0.5 shrink-0" />
                            <span>
                              <strong>German Visa Delay Alert:</strong> Visa appointments in Dhaka take 2.5+ years. APS verification is mandatory before booking.
                            </span>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>
      
    </div>
  );
}
