const fs = require('fs');
const filePath = 'e:/PROJECT/GradPlanner/frontend/public/countries/job-market.json';
let data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

const upgrades = [
  {
    country: "Japan",
    countryCode: "JP",
    overallJobMarketScore: 80,
    demandLevel: "Very High",
    demandTrend: "Exploding — acute AI talent shortage; government mandated digital transformation",
    marketSaturation: "Low",
    averageTimeToJob: "3-6 months",
    averageTimeToJobDays: 120,
    jobOpeningsAnnual: 40000,
    aiMlSpecificOpenings: 12000,
    competitionLevel: 45,
    jobSecurityScore: 92,
    startupEcosystemScore: 72,
    researchPositionsScore: 85,
    remoteWorkCulture: 65,
    workLifeBalanceScore: 62,
    careerProgressionScore: 72,
    majorHubs: ["Tokyo", "Osaka", "Fukuoka", "Kyoto"],
    topEmployers: ["SoftBank (AI division)", "NTT Data", "Fujitsu AI Lab", "Recruit Holdings", "LINE (LY Corporation)", "Sony AI", "Preferred Networks", "RIKEN AIP", "Toyota Research Institute", "NEC AI Research"],
    emergingCompanies: ["Sakana AI", "PKSHA Technology", "BrainPad", "LeapMind", "Abeja"],
    skillsInDemand: ["LLM fine-tuning (Japanese language models)", "Computer Vision (manufacturing QA)", "Robotics AI (Toyota, Honda)", "Healthcare AI", "Predictive maintenance", "MLOps at scale"],
    industriesHiring: [
      { sector: "Manufacturing AI & Robotics", demandScore: 95, salaryRange: "JPY 7,000,000-12,000,000/year", note: "Toyota, Honda, Panasonic — Japan is world's robotics capital; massive AI investment for automated QA" },
      { sector: "Telecom & Platforms", demandScore: 88, salaryRange: "JPY 7,000,000-13,000,000/year", note: "SoftBank, NTT, LINE/LY Corp — recommendation systems, Japanese NLP, ad tech AI" },
      { sector: "Finance & InsurTech AI", demandScore: 85, salaryRange: "JPY 8,000,000-14,000,000/year", note: "Mitsubishi UFJ, Nomura, Tokio Marine — risk ML, fraud detection; huge digital transformation investment" },
      { sector: "Gaming", demandScore: 82, salaryRange: "JPY 7,000,000-12,000,000/year", note: "Nintendo, Capcom, Square Enix, Cygames — procedural generation, NPC AI, computer vision" },
      { sector: "Healthcare AI", demandScore: 88, salaryRange: "JPY 7,500,000-13,000,000/year", note: "Aging population creating world's largest healthcare AI opportunity; massive unmet demand" }
    ],
    entryLevelReality: { easiestEntry: "English-friendly companies: Preferred Networks, Sakana AI, RIKEN AIP, multinational Japanese arms", hardestEntry: "Traditional zaibatsu (NEC, Fujitsu, NTT Data) without Japanese language", sweetSpot: "AI startups in Tokyo (Sakana AI, PKSHA) — English culture, high salaries, equity", bangladeshiPresence: "Very small; ~3,000 BD nationals in Japan; halal food available in Tokyo (Shinjuku halal district)", biasLevel: "Medium — Japanese language critical for 80% of companies; English-friendly firms are minority but growing" },
    visaSponsorshipReality: { willingnessScore: 82, pospWpgpAdvantage: "Designated Activities visa (post-graduation job seeking, 1yr); then Engineer/Specialist in Humanities visa", studyPermitToPgwpSuccess: 85, sponsorshipCost: "Low", note: "Highly Skilled Professional (HSP) points system: 70+ points. PhD + tech job + age bonus = very fast track. HSP = PR in just 1-3 years!" },
    salaryExpectations: { phdEntryLevel: "JPY 8,000,000-12,000,000/year", mscEntryLevel: "JPY 6,000,000-9,000,000/year", midLevel3to5yrs: "JPY 9,000,000-15,000,000/year", seniorLevel: "JPY 13,000,000-25,000,000/year", totalCompNote: "High nominal salaries after years of wage stagnation; yen weakness makes purchasing power higher for foreign goods but lower for remittance" },
    geographicVariation: {
      tokyo: { jobDensity: 95, avgSalary: "JPY 8,500,000", costOfLivingIndex: 78, netBenefit: "60% of Japan's AI jobs; expensive by local standards but cheap vs NY/London; 1BR JPY 100,000-180,000/month" },
      osaka: { jobDensity: 65, avgSalary: "JPY 7,500,000", costOfLivingIndex: 68, netBenefit: "Panasonic, Sharp AI divisions; best food city in world; more affordable than Tokyo" },
      fukuoka: { jobDensity: 52, avgSalary: "JPY 7,000,000", costOfLivingIndex: 60, netBenefit: "Government-designated startup hub; low cost; fast-growing; Sony Semiconductor nearby" }
    },
    workCulture: { averageHoursPerWeek: 48, vacationDays: 10, sickLeaveDays: "No statutory sick leave; many companies pay but culture discourages use", parentalLeaveWeeks: 52, workFromHomeAcceptance: 65, diversityScore: 60, burnoutRisk: "High", culturalFit: "Hierarchical; perfectionist; consensus-driven ringi system; significant overtime culture; however improving rapidly in tech" },
    careerGrowth: { pathToSenior: "5-8 years (traditional firms), 3-5 years (startups)", pathToStaffPrincipal: "12-15 years traditional, 7-10 years startup", managementOpportunities: 65, technicalLadder: "Poorly developed at traditional firms; improving at startups", entrepreneurshipSupport: 72, note: "J-Startup program; METI AI strategy funding; Fukuoka startup corridor" },
    foreignCredentialRecognition: { canadianMasterScore: 80, topUsPhd: 92, topEuPhd: 85, bangladeshUndergrad: 58, note: "Japanese preference for domestic qualifications; top US PhD highly valued; BUET/AUST reputation slowly building" },
    layoffRisk2027to2029: { riskScore: 20, trend: "Extremely stable; Japanese labor market has near-zero layoff culture; companies restructure through attrition only", protection: "Among the most protective employment frameworks globally; termination requires extreme justification" },
    prPathwayIntegration: { jobRequiredForPr: true, skillClassEligibility: 90, crsPointsFromJob: "N/A", provinceNominationBoost: "N/A", note: "Highly Skilled Professional (HSP) visa: 70+ points → PR in 3 years; 80+ points → PR in 1 year. PhD+AI job likely = 80+ points. FASTEST PR for highly qualified." },
    longTermOutlook: { outlook2030: "Very strong — government JPY 4 trillion AI investment; labor shortage structural due to demographics", outlook2040: "Excellent — Japan NEEDS immigrants structurally; AI talent shortage will only worsen; PR reforms will continue", riskFactors: "Language barrier (JLPT N2 for citizenship); work culture burnout; natural disasters (earthquakes); social isolation" },
    strategicAdvice: "Japan's HSP visa is the best-kept secret for Bangladeshi CS/AI PhDs. 80+ HSP points (PhD + AI job + under 30) gives PR in ONE YEAR. MEXT scholarship pays full tuition + JPY 144,000/month. STRATEGY: MEXT → Top Japanese university PhD → AI startup (Preferred Networks/Sakana AI) → HSP points → PR in 1yr. Learn JLPT N3 during studies; N2 for citizenship. Critical warning: work culture in traditional firms is brutal — only target English-friendly companies.",
    confidenceScore: 88,
    dataQuality: "High"
  },
  {
    country: "South Korea",
    countryCode: "KR",
    overallJobMarketScore: 82,
    demandLevel: "Very High",
    demandTrend: "Exploding — Samsung, Hyundai, LG, Kakao massive AI investment",
    marketSaturation: "Low",
    averageTimeToJob: "3-5 months",
    averageTimeToJobDays: 105,
    jobOpeningsAnnual: 35000,
    aiMlSpecificOpenings: 10000,
    competitionLevel: 50,
    jobSecurityScore: 85,
    startupEcosystemScore: 85,
    researchPositionsScore: 82,
    remoteWorkCulture: 68,
    workLifeBalanceScore: 65,
    careerProgressionScore: 80,
    majorHubs: ["Seoul (Gangnam)", "Pangyo (Korea's Silicon Valley)", "Daejeon (KAIST)", "Busan"],
    topEmployers: ["Samsung AI Research Center", "LG AI Research", "Kakao (Korea's Google)", "Naver AI Lab", "Hyundai Motor AI", "SK Telecom AI", "KRAFTON (gaming)", "Krafton/PUBG", "KT (telecom AI)", "POSCO (steel AI)"],
    emergingCompanies: ["Wrtn Technologies", "Rebellions (AI chip)", "Hyperconnect (acquired by Match)", "DeepNatural", "Moloco"],
    skillsInDemand: ["Semiconductor AI (Samsung HBM)", "Korean NLP (Hyperclova)", "Computer Vision (Hyundai autonomous)", "Robotics AI", "Gaming AI (KRAFTON)", "AI chip design (Rebellions)"],
    industriesHiring: [
      { sector: "Semiconductors & AI Chips", demandScore: 98, salaryRange: "KRW 60,000,000-120,000,000/year", note: "Samsung (HBM memory for AI), SK Hynix — world's AI chip supply chain; Rebellions (Korean AI chip startup) growing fast" },
      { sector: "Big Tech Platform AI", demandScore: 92, salaryRange: "KRW 70,000,000-130,000,000/year", note: "Kakao, Naver, LINE — HyperCLOVA X (Korean GPT-4 equivalent), recommendation at massive scale" },
      { sector: "Automotive AI", demandScore: 88, salaryRange: "KRW 65,000,000-110,000,000/year", note: "Hyundai, Kia — autonomous driving AI, Boston Dynamics (owned by Hyundai) robotics" },
      { sector: "Gaming & Metaverse", demandScore: 85, salaryRange: "KRW 60,000,000-110,000,000/year", note: "KRAFTON (PUBG), Netmarble, Nexon — game AI, procedural world generation; Korea world #2 gaming nation" },
      { sector: "Telecoms AI", demandScore: 82, salaryRange: "KRW 58,000,000-100,000,000/year", note: "SK Telecom, KT — 5G AI optimization, customer AI, B2B cloud AI platform" }
    ],
    entryLevelReality: { easiestEntry: "GKS scholarship → KAIST/POSTECH PhD → Samsung/Naver (structured international hire pipeline)", hardestEntry: "Kakao, Naver top product teams (Korean language near-mandatory)", sweetSpot: "Samsung AI Research Center (English culture, international team), Rebellions AI chip startup", bangladeshiPresence: "Very small; ~5,000 BD nationals in Korea; halal food available in Seoul (Itaewon)", biasLevel: "Medium — Korean language for 70% of companies; English-friendly culture growing at Samsung/Hyundai research arms" },
    visaSponsorshipReality: { willingnessScore: 85, pospWpgpAdvantage: "D-10 job seeker visa (6 months); then E-7 (Specially Designated Activities) for tech roles", studyPermitToPgwpSuccess: 88, sponsorshipCost: "Low", note: "KIIP (Korea Immigration Integration Program) for PR. Point-based system similar to Japan HSP." },
    salaryExpectations: { phdEntryLevel: "KRW 70,000,000-100,000,000/year", mscEntryLevel: "KRW 55,000,000-80,000,000/year", midLevel3to5yrs: "KRW 80,000,000-120,000,000/year", seniorLevel: "KRW 120,000,000-200,000,000/year", totalCompNote: "Samsung/LG pay globally competitive; equity rare but bonus (성과급) can be 100-200% of salary; annual pay raises negotiable" },
    geographicVariation: {
      seoul_gangnam: { jobDensity: 90, avgSalary: "KRW 85,000,000", costOfLivingIndex: 75, netBenefit: "Kakao, Naver, Samsung HQ proximity; 1BR KRW 1,500,000-2,500,000/month — affordable vs Western cities" },
      pangyo: { jobDensity: 88, avgSalary: "KRW 82,000,000", costOfLivingIndex: 72, netBenefit: "Korea's tech valley — Kakao, Krafton, many AI startups; 20min from Seoul; slightly cheaper" },
      daejeon: { jobDensity: 65, avgSalary: "KRW 70,000,000", costOfLivingIndex: 60, netBenefit: "KAIST, ETRI (government AI research) — research-focused; very affordable; university city" }
    },
    workCulture: { averageHoursPerWeek: 52, vacationDays: 15, sickLeaveDays: "Very limited; presenteeism culture strong", parentalLeaveWeeks: 52, workFromHomeAcceptance: 60, diversityScore: 62, burnoutRisk: "Very High", culturalFit: "Hierarchical; Confucian respect for seniority; hard-working culture (ppalli ppalli — hurry hurry); improving at startups" },
    careerGrowth: { pathToSenior: "5-8 years", pathToStaffPrincipal: "10-15 years at chaebols; faster at startups", managementOpportunities: 70, technicalLadder: "Developing rapidly; Samsung and Naver have distinct IC tracks", entrepreneurshipSupport: 88, note: "K-ICT startup support; TIPS (Technology Innovation Program); government provides KRW 500M to startups" },
    foreignCredentialRecognition: { canadianMasterScore: 82, topUsPhd: 95, topEuPhd: 88, bangladeshUndergrad: 58, note: "KAIST/POSTECH (Korean top universities) degree = elite credential; US PhD from top school is highly respected; domestic degree preferred at traditional chaebols" },
    layoffRisk2027to2029: { riskScore: 35, trend: "Stable; chaebol employment culturally permanent; startup sector more volatile but AI roles protected", protection: "Korean Labor Standards Act; mass layoffs require government approval; chaebols culturally avoid layoffs" },
    prPathwayIntegration: { jobRequiredForPr: true, skillClassEligibility: 88, crsPointsFromJob: "N/A", provinceNominationBoost: "N/A", note: "F-2 (Resident) → F-5 (Permanent Resident) after 5 years. Requires TOPIK Level 4 (Korean language). 5-year PR then 5 more years for citizenship. Language is the primary barrier." },
    longTermOutlook: { outlook2030: "Very strong — Samsung HBM AI chip dominance; Hyundai robotics; government KRW 9 trillion AI investment", outlook2040: "Strong — demographic crisis (world's lowest birth rate) creates massive structural immigration need; Korea NEEDS immigrants", riskFactors: "TOPIK Level 4 requirement for PR (significant language investment); geopolitical risk (North Korea proximity); work-life burnout" },
    strategicAdvice: "South Korea is exceptional for AI/semiconductor specialists. GKS scholarship pays full tuition + KRW 1,000,000/month — start here. Samsung AI Research Center and Naver AI Lab are world-class. STRATEGY: GKS → KAIST PhD → Samsung AI Research (English-friendly) → 5 years → PR with TOPIK 4. KEY RISK: TOPIK 4 is genuinely difficult (equivalent to C1 Korean). Start Korean language study on Day 1 of arrival. The demographic crisis means Korea WILL liberalize immigration — position yourself early.",
    confidenceScore: 88,
    dataQuality: "High"
  },
  {
    country: "China",
    countryCode: "CN",
    overallJobMarketScore: 78,
    demandLevel: "Extremely High",
    demandTrend: "Explosive — world's #2 AI ecosystem with government mandate",
    marketSaturation: "Low for top roles",
    averageTimeToJob: "2-4 months",
    averageTimeToJobDays: 90,
    jobOpeningsAnnual: 500000,
    aiMlSpecificOpenings: 150000,
    competitionLevel: 88,
    jobSecurityScore: 65,
    startupEcosystemScore: 95,
    researchPositionsScore: 90,
    remoteWorkCulture: 60,
    workLifeBalanceScore: 40,
    careerProgressionScore: 90,
    majorHubs: ["Beijing (Zhongguancun)", "Shanghai", "Shenzhen", "Hangzhou"],
    topEmployers: ["Alibaba (DAMO Academy)", "Tencent AI Lab", "Baidu (AI Cloud)", "ByteDance (TikTok AI)", "Huawei Noah's Ark Lab", "Meituan", "JD.com AI", "Xiaomi AI", "DJI (drone AI)", "OPPO Research"],
    emergingCompanies: ["DeepSeek", "Moonshot AI", "Zhipu AI", "Manus AI", "Stepfun"],
    skillsInDemand: ["LLM training at scale (Chinese language models)", "Computer Vision (surveillance, autonomous)", "Recommendation AI (ByteDance scale)", "Drone AI (DJI)", "Semiconductor AI (domestic chips post-US sanctions)"],
    industriesHiring: [
      { sector: "Big Tech Platform AI", demandScore: 98, salaryRange: "CNY 600,000-1,500,000/year", note: "ByteDance, Alibaba, Tencent — world's largest recommendation systems; AI at billions-of-users scale" },
      { sector: "Autonomous Vehicles", demandScore: 92, salaryRange: "CNY 700,000-1,500,000/year", note: "BYD, Li Auto, Baidu Apollo, Pony.ai — world's largest autonomous vehicle testing ground" },
      { sector: "Hardware & Drones", demandScore: 90, salaryRange: "CNY 500,000-1,200,000/year", note: "DJI (controls 70% of global drone market), Xiaomi robotics; embedded AI at massive scale" },
      { sector: "AI Foundation Models", demandScore: 95, salaryRange: "CNY 800,000-2,000,000/year", note: "DeepSeek (shocked world with R1), Moonshot AI, Zhipu AI — China's OpenAI race; intensely funded" },
      { sector: "E-commerce & Retail AI", demandScore: 88, salaryRange: "CNY 500,000-1,000,000/year", note: "Alibaba, JD.com, Pinduoduo — logistics AI, computer vision for quality control, recommendation" }
    ],
    entryLevelReality: { easiestEntry: "International hire programs at ByteDance, Alibaba (they actively recruit globally)", hardestEntry: "Huawei (security clearance for foreigners complex post-US sanctions)", sweetSpot: "DeepSeek, Moonshot AI — cutting-edge research, English culture, world-class team", bangladeshiPresence: "Growing; CSC scholarship alumni community; Mandarin essential for daily life", biasLevel: "Medium — Chinese language critical for life outside work; professional English used at top tech firms" },
    visaSponsorshipReality: { willingnessScore: 80, pospWpgpAdvantage: "Work visa (Z visa) → Residence Permit for Employment; CSC scholarship alumni have strong employer network", studyPermitToPgwpSuccess: 80, sponsorshipCost: "Low", note: "China Talent visa (Type A/B) for high-skilled workers: fast-track. ByteDance/Alibaba have dedicated global mobility teams." },
    salaryExpectations: { phdEntryLevel: "CNY 700,000-1,200,000/year", mscEntryLevel: "CNY 400,000-700,000/year", midLevel3to5yrs: "CNY 800,000-1,500,000/year", seniorLevel: "CNY 1,500,000-3,000,000+/year", totalCompNote: "Top AI salaries globally at DeepSeek/ByteDance level; equity in pre-IPO companies can be life-changing; BUT geopolitical risk to equity value is real" },
    geographicVariation: {
      beijing: { jobDensity: 90, avgSalary: "CNY 650,000", costOfLivingIndex: 70, netBenefit: "Baidu, ByteDance HQ, Tsinghua/PKU AI labs — China's Silicon Valley; 1BR CNY 6,000-10,000/month" },
      shanghai: { jobDensity: 85, avgSalary: "CNY 620,000", costOfLivingIndex: 75, netBenefit: "Most international; Alibaba financial affiliate, Tesla AI, JP Morgan tech; expat-friendly" },
      shenzhen: { jobDensity: 82, avgSalary: "CNY 600,000", costOfLivingIndex: 72, netBenefit: "Hardware AI capital (DJI, Huawei, Tencent HQ); fastest growing tech city; near Hong Kong" },
      hangzhou: { jobDensity: 78, avgSalary: "CNY 580,000", costOfLivingIndex: 65, netBenefit: "Alibaba HQ — e-commerce AI at unimaginable scale; beautiful city; most affordable major hub" }
    },
    workCulture: { averageHoursPerWeek: 60, vacationDays: 5, sickLeaveDays: "Limited; 996 culture (9am-9pm, 6 days) is still real at top firms despite legal limits", parentalLeaveWeeks: 14, workFromHomeAcceptance: 55, diversityScore: 60, burnoutRisk: "Extreme", culturalFit: "Intensely competitive; speed above all; guanxi (relationships) matter enormously; face culture critical" },
    careerGrowth: { pathToSenior: "2-4 years (fastest in world)", pathToStaffPrincipal: "6-8 years at top firms", managementOpportunities: 90, technicalLadder: "Rapidly developing", entrepreneurshipSupport: 98, note: "China produces more AI startups than any other country; government grants, VC ecosystem world-class post-DeepSeek" },
    foreignCredentialRecognition: { canadianMasterScore: 80, topUsPhd: 98, topEuPhd: 90, bangladeshUndergrad: 55, note: "US PhD from top school is the highest-value credential in China AI; CSC scholarship Chinese university PhD respected" },
    layoffRisk2027to2029: { riskScore: 72, trend: "High volatility; regulatory crackdowns (Alibaba 2021, gaming 2022, now AI regulation); US-China tech war creates uncertainty", protection: "Chinese labor law mandatory severance (N+1 months); however enforcement patchy at large firms" },
    prPathwayIntegration: { jobRequiredForPr: true, skillClassEligibility: 65, crsPointsFromJob: "N/A", provinceNominationBoost: "N/A", note: "China PR (Permanent Residence Certificate) is extremely difficult for non-Chinese. No realistic pathway for Bangladeshi tech workers. Treat as 3-5 year career accelerator, not permanent home." },
    longTermOutlook: { outlook2030: "Strong for AI careers — DeepSeek shock shows China is reaching parity with US in AI; massive government investment", outlook2040: "Uncertain — US-China tech decoupling creates risk; however China's internal AI market self-sustains; demographic decline", riskFactors: "US-China tech war (US sanctions, export controls); no realistic PR path; great firewall restrictions; regulatory unpredictability" },
    strategicAdvice: "China offers the fastest career acceleration in the world for AI engineers willing to work 80+ hours/week. CSC scholarship (free tuition + stipend) is the entry point. DeepSeek and Moonshot AI are comparable to OpenAI in technical sophistication. CRITICAL STRATEGY: China should be used as a 3-5 year high-intensity career springboard — build your portfolio, publications, and savings — then leverage those credentials for PR in Canada/Australia/Germany. DO NOT plan to settle permanently.",
    confidenceScore: 85,
    dataQuality: "High"
  },
  {
    country: "France",
    countryCode: "FR",
    overallJobMarketScore: 80,
    demandLevel: "High",
    demandTrend: "Strong and accelerating — France 2030 AI investment plan",
    marketSaturation: "Medium",
    averageTimeToJob: "3-5 months",
    averageTimeToJobDays: 110,
    jobOpeningsAnnual: 25000,
    aiMlSpecificOpenings: 7000,
    competitionLevel: 68,
    jobSecurityScore: 90,
    startupEcosystemScore: 88,
    researchPositionsScore: 88,
    remoteWorkCulture: 82,
    workLifeBalanceScore: 85,
    careerProgressionScore: 78,
    majorHubs: ["Paris (Station F)", "Grenoble", "Lyon", "Toulouse", "Sophia Antipolis"],
    topEmployers: ["Mistral AI (Paris)", "Google DeepMind Paris", "Meta AI Research Paris", "Thales (defense AI)", "Airbus (aerospace AI)", "BNP Paribas Tech", "Capgemini AI", "Schneider Electric AI", "INRIA", "CEA Tech"],
    emergingCompanies: ["Mistral AI", "Bioptimus", "Nabla", "Contentsquare", "Shift Technology"],
    skillsInDemand: ["Foundation model training (Mistral)", "Aerospace AI (Airbus)", "Defense AI (Thales)", "Healthcare AI", "French NLP", "EU AI Act compliance architecture"],
    industriesHiring: [
      { sector: "AI Foundation Models", demandScore: 95, salaryRange: "EUR 90,000-180,000", note: "Mistral AI is Europe's most valuable AI company (EUR 6B valuation) — building LLMs competitive with GPT-4; Paris becomes Europe's AI capital" },
      { sector: "Aerospace & Defense AI", demandScore: 90, salaryRange: "EUR 65,000-110,000", note: "Airbus (Toulouse HQ), Thales, Dassault — AI for aircraft systems, autonomous defense; EU's largest aerospace market" },
      { sector: "Research Institutions", demandScore: 88, salaryRange: "EUR 55,000-85,000", note: "INRIA (world-renowned AI research), CEA Tech, CNRS — France's strong public AI research ecosystem; Turing Institute equivalent" },
      { sector: "Banking & FinTech", demandScore: 85, salaryRange: "EUR 70,000-120,000", note: "BNP Paribas, Société Générale, Crédit Agricole — algorithmic trading AI, fraud detection, wealth management ML" },
      { sector: "Luxury & Retail AI", demandScore: 78, salaryRange: "EUR 60,000-100,000", note: "LVMH (Louis Vuitton parent), L'Oréal — customer personalization AI; France's unique luxury sector AI applications" }
    ],
    entryLevelReality: { easiestEntry: "INRIA research positions (English culture), Capgemini AI graduate programs", hardestEntry: "Mistral AI core research team (world-class competition)", sweetSpot: "Bioptimus, Nabla, or Contentsquare — well-funded Paris startups with international culture", bangladeshiPresence: "Moderate; established South Asian community in Paris (approximately 100,000 Bangladeshi nationals in France)", biasLevel: "Medium — French language strongly preferred for integration; Station F ecosystem is very international" },
    visaSponsorshipReality: { willingnessScore: 82, pospWpgpAdvantage: "Passeport Talent (Talent Passport) — specifically for highly qualified researchers and tech workers; fast 4-week processing", studyPermitToPgwpSuccess: 86, sponsorshipCost: "Low", note: "Passeport Talent: Salarié qualifié (qualified employee) — salary > EUR 39,151 → 4-year renewable visa with immediate work rights. Easiest skilled migration in EU after Netherlands." },
    salaryExpectations: { phdEntryLevel: "EUR 70,000-100,000/year", mscEntryLevel: "EUR 50,000-75,000/year", midLevel3to5yrs: "EUR 75,000-110,000/year", seniorLevel: "EUR 110,000-180,000/year", totalCompNote: "Salaries appear lower gross but 35-hour work week, 5 weeks mandatory vacation, and comprehensive state healthcare dramatically increase effective compensation" },
    geographicVariation: {
      paris: { jobDensity: 92, avgSalary: "EUR 75,000", costOfLivingIndex: 88, netBenefit: "Mistral AI, Station F startups, INRIA Paris, Google Paris — world-class AI hub; 1BR EUR 1,500-2,500/month" },
      grenoble: { jobDensity: 68, avgSalary: "EUR 62,000", costOfLivingIndex: 70, netBenefit: "Semiconductor capital (STMicroelectronics), CEA research; university town; very affordable; stunning Alps backdrop" },
      toulouse: { jobDensity: 72, avgSalary: "EUR 60,000", costOfLivingIndex: 68, netBenefit: "Airbus headquarters — aerospace AI; vibrant student city; affordable; strong engineering tradition" },
      sophia_antipolis: { jobDensity: 65, avgSalary: "EUR 65,000", costOfLivingIndex: 75, netBenefit: "Europe's Silicon Valley; SAP, Oracle, Amadeus; Mediterranean lifestyle; near Nice" }
    },
    workCulture: { averageHoursPerWeek: 35, vacationDays: 25, sickLeaveDays: "90 days full pay via Securite Sociale after 1yr employment", parentalLeaveWeeks: 16, workFromHomeAcceptance: 82, diversityScore: 80, burnoutRisk: "Low", culturalFit: "Work to live, not live to work; lunch breaks sacrosanct; intellectual debate highly valued; direct feedback expected" },
    careerGrowth: { pathToSenior: "4-6 years", pathToStaffPrincipal: "8-12 years", managementOpportunities: 78, technicalLadder: "Growing rapidly at Mistral/startup ecosystem", entrepreneurshipSupport: 88, note: "Station F (world's largest startup campus) in Paris; BPI France public investment bank for startups; French Tech Next40 elite program" },
    foreignCredentialRecognition: { canadianMasterScore: 85, topUsPhd: 92, topEuPhd: 92, bangladeshUndergrad: 60, note: "Grande École (Polytechnique, CentraleSupélec) degree = French elite credential; ENIC-NARIC France for foreign credential recognition" },
    layoffRisk2027to2029: { riskScore: 35, trend: "Very stable; French labor law makes layoffs extremely expensive; PSE (social plan) process takes months", protection: "World's strongest employment protection; CDI (permanent contract) practically irrevocable; even startups hesitate to lay off" },
    prPathwayIntegration: { jobRequiredForPr: true, skillClassEligibility: 88, crsPointsFromJob: "N/A", provinceNominationBoost: "N/A", note: "5 years legal residence → Carte de Résident (PR). Passeport Talent → 4yr visa → PR at year 5. French B1 language required. Citizenship at year 10 (or year 5 for exceptional contribution)." },
    longTermOutlook: { outlook2030: "Very strong — France 2030 plan investing EUR 22B in AI/quantum/green tech; Mistral AI puts France on global AI map", outlook2040: "Strong — EU's core economic engine; nuclear energy AI leadership; aerospace AI world-class", riskFactors: "Political instability (frequent government changes, strikes); French language mandatory for true integration; high income tax" },
    strategicAdvice: "France is Europe's most exciting AI destination in 2026. Mistral AI's success has created a vibrant Paris AI ecosystem. The Passeport Talent makes work permit trivially easy for AI graduates. STRATEGY: INRIA PhD or Ecole Polytechnique master's → Mistral AI or INRIA research → Passeport Talent → 5yr PR. CRITICAL: French B1 mandatory for PR. Enroll in Alliance Française in Dhaka 18 months before departure — this single investment will transform your French options.",
    confidenceScore: 90,
    dataQuality: "High"
  },
  {
    country: "United Arab Emirates",
    countryCode: "AE",
    overallJobMarketScore: 85,
    demandLevel: "Very High",
    demandTrend: "Explosive — government-mandated AI transformation; MBZUAI world-class",
    marketSaturation: "Low",
    averageTimeToJob: "1-3 months",
    averageTimeToJobDays: 60,
    jobOpeningsAnnual: 30000,
    aiMlSpecificOpenings: 8000,
    competitionLevel: 55,
    jobSecurityScore: 75,
    startupEcosystemScore: 82,
    researchPositionsScore: 85,
    remoteWorkCulture: 72,
    workLifeBalanceScore: 72,
    careerProgressionScore: 90,
    majorHubs: ["Dubai (DIFC)", "Abu Dhabi (Masdar City)", "Sharjah"],
    topEmployers: ["G42 (Abu Dhabi AI government arm)", "MBZUAI (research)", "Presight AI", "Microsoft UAE", "Amazon AWS UAE", "Oracle UAE", "Etisalat/e& (telecom AI)", "Careem (Uber subsidiary)", "Property Finder", "Noon.com"],
    emergingCompanies: ["Aleph Alpha UAE", "Falcon LLM team (TII)", "Cafu (fuel delivery AI)", "Anghami (music AI)"],
    skillsInDemand: ["Arabic NLP (Falcon LLM)", "Healthcare AI (Cleveland Clinic Abu Dhabi)", "FinTech AI (DIFC)", "Smart city AI (UAE government projects)", "Cloud AI (Microsoft/AWS local expansion)", "Cybersecurity AI"],
    industriesHiring: [
      { sector: "Government AI & Smart City", demandScore: 95, salaryRange: "AED 20,000-45,000/month", note: "G42 (backed by Sheikh Tahnoon) runs UAE's AI strategy — massive government contracts, Falcon LLM, genome sequencing AI; almost no competition from locals" },
      { sector: "Financial Services AI", demandScore: 90, salaryRange: "AED 25,000-55,000/month", note: "DIFC (Dubai International Financial Centre) — hundreds of FinTech companies; fraud detection, quantitative trading, wealth AI" },
      { sector: "Research Institutions", demandScore: 92, salaryRange: "AED 22,000-40,000/month + housing", note: "MBZUAI (Mohamed bin Zayed University of AI) — world's first AI-focused university; full scholarship for MSc/PhD + AED 9,300/month stipend; top research" },
      { sector: "Telecoms AI", demandScore: 85, salaryRange: "AED 18,000-38,000/month", note: "e& (Etisalat) — network optimization AI, 5G, smart home; largest telecom in MENA" },
      { sector: "E-commerce & Delivery", demandScore: 82, salaryRange: "AED 18,000-35,000/month", note: "Careem (Uber MENA), Noon.com, Talabat — logistics optimization, demand forecasting, recommendation" }
    ],
    entryLevelReality: { easiestEntry: "MBZUAI (scholarship = automatic entry), G42 international recruitment pipeline", hardestEntry: "Private bank quant roles (Goldman, JPMorgan UAE — prefer Oxbridge/Ivy credentials)", sweetSpot: "G42 AI engineer or Microsoft UAE — largest AI employer in region, English-only culture, international team", bangladeshiPresence: "Very large — Bangladesh is one of the top 3 expat communities in UAE (~1.5M Bangladeshis); established community in Dubai (Deira, Bur Dubai)", biasLevel: "Low professionally for tech roles; large BD community means cultural comfort; Bangladeshi passport holders very common in UAE" },
    visaSponsorshipReality: { willingnessScore: 95, pospWpgpAdvantage: "MBZUAI arranges student visa and then employment visa — zero bureaucracy for students; employer handles all", studyPermitToPgwpSuccess: 96, sponsorshipCost: "Zero (employer pays)", note: "UAE Golden Visa (10yr) available for AI specialists — salary > AED 30,000 OR MBZUAI graduate. Golden Visa = long-term stability without employment dependency (unlike standard residency)." },
    salaryExpectations: { phdEntryLevel: "AED 25,000-40,000/month (tax-free)", mscEntryLevel: "AED 18,000-30,000/month (tax-free)", midLevel3to5yrs: "AED 30,000-50,000/month (tax-free)", seniorLevel: "AED 50,000-100,000+/month (tax-free)", totalCompNote: "100% tax-free. Every AED earned hits your bank. AED 25,000/month = approximately USD 6,800/month take-home, every month. Housing often provided or allowance given." },
    geographicVariation: {
      dubai: { jobDensity: 88, avgSalary: "AED 28,000/month", costOfLivingIndex: 85, netBenefit: "FinTech, e-commerce, hospitality AI; most international city; 1BR AED 7,000-15,000/month in Marina/Downtown" },
      abu_dhabi: { jobDensity: 82, avgSalary: "AED 30,000/month", costOfLivingIndex: 80, netBenefit: "G42, MBZUAI, Masdar City — government AI and research; less nightlife, more stable; 1BR AED 6,000-12,000/month" },
      sharjah: { jobDensity: 55, avgSalary: "AED 22,000/month", costOfLivingIndex: 65, netBenefit: "University of Sharjah; more affordable; commutable to Dubai (30min); growing tech scene" }
    },
    workCulture: { averageHoursPerWeek: 45, vacationDays: 30, sickLeaveDays: "15 days full pay", parentalLeaveWeeks: 5, workFromHomeAcceptance: 72, diversityScore: 95, burnoutRisk: "Medium", culturalFit: "Multicultural — 90 nationalities in major tech firms; English universal; Ramadan schedule changes; alcohol restricted to licensed venues" },
    careerGrowth: { pathToSenior: "3-5 years", pathToStaffPrincipal: "6-10 years", managementOpportunities: 85, technicalLadder: "Rapidly developing at G42, MBZUAI spin-outs", entrepreneurshipSupport: 90, note: "Dubai Future Foundation; Hub71 (Abu Dhabi's startup ecosystem) provides seed funding + visa + housing for startups; zero corporate tax for tech companies" },
    foreignCredentialRecognition: { canadianMasterScore: 88, topUsPhd: 95, topEuPhd: 92, bangladeshUndergrad: 68, note: "MBZUAI degree is rapidly gaining international recognition; US/EU PhD very highly valued; BUET/AUST degrees recognized, BD community well-known" },
    layoffRisk2027to2029: { riskScore: 60, trend: "Higher than EU — visa tied to employment for standard workers; global tech downturn = visa cancellation risk; Golden Visa holders are protected", protection: "End of Service Gratuity (21 days/year × years served) mandatory; DEWS (savings scheme) for DIFC workers; no other protection for non-Golden Visa" },
    prPathwayIntegration: { jobRequiredForPr: true, skillClassEligibility: 90, crsPointsFromJob: "N/A", provinceNominationBoost: "N/A", note: "CRITICAL: There is NO traditional PR in UAE. Golden Visa (10yr renewable) is the equivalent but IS NOT citizenship. HIV-positive individuals are deported under UAE law. No naturalization pathway exists for non-Arabs. Plan UAE as a 5-10yr wealth accumulation phase, not a permanent home." },
    longTermOutlook: { outlook2030: "Very strong — Vision 2031 UAE AI strategy is state-level priority; G42 and Falcon LLM world-class", outlook2040: "Uncertain — extreme heat (>50°C increasingly common), lack of PR/citizenship, and US-China tensions create long-term risks", riskFactors: "NO citizenship or PR pathway; extreme climate (increasingly unlivable outdoors summers); geopolitical Middle East risk; Golden Visa ≠ PR" },
    strategicAdvice: "UAE is the ultimate wealth-building accelerator for Bangladeshi AI graduates. Tax-free salaries, MBZUAI full scholarship, and the largest Bangladeshi community outside Bangladesh create a uniquely comfortable environment. STRATEGY: MBZUAI scholarship → G42 or MBZUAI research role → Golden Visa (10yr) → accumulate AED 1-2 million in savings → use savings + experience to move to Canada/Ireland/Germany for PR. NEVER plan UAE as your final destination. The Golden Visa gives you 10 years of security — use them wisely.",
    confidenceScore: 92,
    dataQuality: "High"
  }
];

upgrades.forEach(upgrade => {
  const idx = data.jobMarkets.findIndex(j => j.country === upgrade.country);
  if (idx !== -1) {
    data.jobMarkets[idx] = upgrade;
  } else {
    data.jobMarkets.push(upgrade);
  }
});

fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
console.log('job-market.json: Japan, South Korea, China, France, UAE upgraded!');
