export const countryList = [
  { name: "Australia", id: "Australia" },
  { name: "Austria", id: "Austria" },
  { name: "Belgium", id: "Belgium" },
  { name: "Canada", id: "Canada" },
  { name: "China", id: "China" },
  { name: "Denmark", id: "Denmark" },
  { name: "Finland", id: "Finland" },
  { name: "France", id: "France" },
  { name: "Germany", id: "Germany" },
  { name: "Ireland", id: "Ireland" },
  { name: "Japan", id: "Japan" },
  { name: "Netherlands", id: "Netherlands" },
  { name: "New Zealand", id: "New Zealand" },
  { name: "Norway", id: "Norway" },
  { name: "Singapore", id: "Singapore" },
  { name: "South Korea", id: "South Korea" },
  { name: "Sweden", id: "Sweden" },
  { name: "Switzerland", id: "Switzerland" },
  { name: "UAE", id: "UAE" },
  { name: "USA", id: "USA" },
];
